steps:
  - id: "Build express-app test docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nodejs-app", "."]

  - id: "Run unit test"
    name: "gcr.io/cloud-builders/docker"
    args: [
      'run', 'gcr.io/$PROJECT_ID/nodejs-app',
      'npm', 'test'
    ]

  - id: "Build express-app production docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nodejs-app", "."]

  - id: "Build nginx-react docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "frontend/Dockerfile", "-t", "gcr.io/$PROJECT_ID/nginx-react", "frontend"]

images:
  - gcr.io/$PROJECT_ID/nodejs-app
  - gcr.io/$PROJECT_ID/nginx-react
