steps:
  - id: "Build test docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/docker-express-typescript", "."]

  - id: "Run unit test"
    name: "gcr.io/cloud-builders/docker"
    args: ["run", "npm", "test"]

  - id: "Build production docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/docker-express-typescript", "."]

  - id: "Deploy"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "docker-express-typescript",
        "--image",
        "gcr.io/$PROJECT_ID/docker-express-typescript",
        "--region",
        "us-central1",
      ]

images:
  - gcr.io/$PROJECT_ID/docker-express-typescript
