steps:
  - id: "Build test docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nodejs-app", "."]

  - id: "Run unit test"
    name: "gcr.io/cloud-builders/docker"
    args: [
      'run', 'gcr.io/$PROJECT_ID/nodejs-app',
      'npm', 'test'
    ]

  - id: "Build production docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nodejs-app", "."]

  - id: "Build nginx docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-f", "nginx/Dockerfile", "."]

images:
  - gcr.io/$PROJECT_ID/nodejs-app
