version: "3"

services:
  app:
    image: devmasx/express-typescript-backend:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000

  front:
    image: devmasx/react-typescript-nginx-frontend:latest
    environment:
      PROXY_PASS: http://app:3000
      API_URL: "/api"
    ports:
      - 80:80
