version: "3"

services:
  app:
    image: devmasx/express-typescript-backend:latest
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    ports:
      - 3000:3000

  front:
    image: devmasx/react-typescript-nginx-frontend:latest
    environment:
      PROXY_PASS: http://app:3000
      API_URL: "/api"
    ports:
      - 8080:80

  # redis:
  #   image: redis
  #    ports:
  #      - "6379:6379"
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      # test: ["CMD", "mysql" ,"-h", "db", "-P", "3306", "-u", "root", "-ppassword", "-e", "'SHOW databases'"]
      test: ["CMD", "mysqladmin", "-h", "db", "-ppassword", "status"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  mysql:
