steps:
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - apply
      - -f
      - kubernetes/nodejs-nginx.yaml
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=nodejs-cluster"
