kind: Service
apiVersion: v1
metadata:
  name: nodejs-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nodejs-nginx
status:
  loadBalancer: {}
